# Generated by Django 3.2.16 on 2022-11-17 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("barber_booking", "0008_auto_20221117_1541"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
