# Generated by Django 3.2.16 on 2022-11-17 15:58

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barber_booking", "0009_alter_booking_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="email",
            field=models.EmailField(
                max_length=254, verbose_name=django.contrib.auth.models.User
            ),
        ),
    ]
