# Generated by Django 3.2.16 on 2022-11-22 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("barber_booking", "0013_booking_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="email",
        ),
    ]
