# Generated by Django 3.2.16 on 2022-11-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_booking', '0015_alter_booking_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
