# Generated by Django 3.2.16 on 2022-11-22 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber_booking', '0016_alter_booking_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='querie',
            options={'ordering': ['-created_on']},
        ),
    ]
