# Generated by Django 3.2.16 on 2022-11-24 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("barber_booking", "0020_alter_booking_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="username",
            field=models.ForeignKey(
                default=3, on_delete=django.db.models.deletion.CASCADE, to="auth.user"
            ),
            preserve_default=False,
        ),
    ]
