# Generated by Django 3.2.16 on 2022-11-27 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber_booking', '0024_alter_booking_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Querie',
            new_name='Query',
        ),
    ]
